ignore:
  - "misc/specs"
  - "misc/tools"
  - "samples"

coverage:
  range: 70..95
  status:
    project:
      default:
        target: 85%
    patch:
      default:
        target: 85%

codecov:
  notify:
    after_n_builds: 8
comment:
  after_n_builds: 8
