version: 2
updates:
  - package-ecosystem: gradle
    directory: "/samples/js/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/jvm/junit5"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/jvm/spek"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: maven
    directory: "/samples/maven"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
  - package-ecosystem: gradle
    directory: "/samples/multiplatform"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
