name: Windows

on: [push, pull_request]

jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: true
            matrix:
                java_version: [9, 10, 12, 13, 14]

        steps:
            -   uses: actions/checkout@v1
            -   name: "Set up JDK ${{ matrix.java_version }}"
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java_version }}
            -   name: buildNonDeprecatedJvm
                run: ./gradlew buildNonDeprecatedJvm
                env:
                  CI: true
            -   name: Upload windows build code coverage
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    flags: current_windows
                    fail_ci_if_error: true

            -   name: build sample atrium tests project
                run: misc\tools\atrium-samples-test\gradlew -p misc\tools\atrium-samples-test build
