name: Windows

on: [push, pull_request]

jobs:
    build:
        runs-on: windows-latest
        strategy:
            fail-fast: true
            matrix:
                java_version: [9, 10, 11, 12, 13, 14]

        steps:
            -   uses: actions/checkout@v1
            -   name: "Set up JDK ${{ matrix.java_version }}"
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java_version }}

            -   name: buildNonDeprecatedJvm
                run: ./gradlew buildNonDeprecatedJvm

            -   name: download Android SDK's android.jar
                run: |
                    curl -o android.jar -L "https://github.com/Sable/android-platforms/blob/master/android-26/android.jar?raw=true"
                    $file_sha256 = $(certutil -hashfile android.jar sha256)[1] -replace " ",""
                    if ($file_sha256 -Ne "cdc1846376a14b0370cc63454a129606b4a52cc50ada75ef0d4cf956b1ad2daa") {
                        echo "wrong sha256 for android.jar: $file_sha256";
                        echo "                    expected: $expected_sha256";
                        exit -1
                    }

            -   name: check Atrium's -android.jar can be dexed
                run: ATRIUM_ANDROID_JAR="$PWD/android.jar" ./gradlew checkDexer
                shell: bash

            -   name: Upload windows build code coverage
                uses: codecov/codecov-action@v1
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    flags: current_windows
                    # too many timeout errors, let's not fail at the moment
                    #fail_ci_if_error: true

            -   name: build jasmine sample
                run: ./gradlew build
                working-directory: samples\js\jasmine

            -   name: build mocha sample
                run: ./gradlew build
                working-directory: samples\js\mocha

            -   name: build Spek sample
                run: ./gradlew build
                working-directory: samples\jvm\spek

            -   name: build Junit5 sample
                run: ./gradlew build
                working-directory: samples\jvm\junit5

            -   name: build MPP sample
                run: ./gradlew build
                working-directory: samples\multiplatform

            -   name: composite build atrium-samples
                run: ./gradlew build
                working-directory: misc\tools\atrium-samples-test

    maven-sample:
        runs-on: windows-latest
        strategy:
            fail-fast: true
        steps:
            -   uses: actions/checkout@v1
            -   name: "Set up JDK ${{ matrix.java_version }}"
                uses: actions/setup-java@v1
                with:
                    java-version: 11
            -   name: build maven sample
                run: "./mvnw -version && ./mvnw -B clean test"
                working-directory: samples/maven
